
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    url: /api.yaml
  api-docs:
    enabled: true

server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: tmf